services:

  
  postgres:
    image: postgres:15
    env_file:
      - .env.singleton
    ports:
      - "15432:5432"
    # environment:
    #   - POSTGRES_USER=POSTGRES_USER
    #   - POSTGRES_PASSWORD=${_POSTGRES_PASSWORD}
    #   - POSTGRES_DB=${_POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    env_file:
      - .env.singleton
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
    command:
      sh -c "npm run migrate:prod && npm start"

  nginx:
    image: nginx:1.25
    ports:
      - '80:80'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ../public:/usr/share/nginx/html/public
    depends_on:
      - app
    networks:
      - app-network

volumes:
  postgres_data:
  
networks:
  app-network:
    driver: bridge
